name: flutter_barcode_sdk
description: The only Flutter barcode SDK for Android, iOS, Web, Windows, Linux, macOS. Supported 1D/2D barcodes include Code39, Code128, EAN13, QR Code, DataMatrix, MaxiCode, PDF417, etc.
version: 2.5.1
homepage: https://www.dynamsoft.com/barcode-reader/overview/
repository: https://github.com/yushulx/flutter_barcode_sdk

environment:
  sdk: ">=2.12.3 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.dynamsoft.flutter_barcode_sdk
        pluginClass: FlutterBarcodeSdkPlugin
      ios:
        pluginClass: FlutterBarcodeSdkPlugin
      windows:
        pluginClass: FlutterBarcodeSdkPlugin
      linux:
        pluginClass: FlutterBarcodeSdkPlugin
      macos:
        pluginClass: FlutterBarcodeSdkPlugin
      web:
        pluginClass: FlutterBarcodeSdkWeb
        fileName: flutter_barcode_sdk_web.dart
